version: '3.8'

services:
  app:
    build: .
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql://postgres:qwerty@db:5432/clinical_recommendations
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=clinical_recommendations
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - MINZDRAV_URL=https://apicr.minzdrav.gov.ru/api.ashx
      - ORIGIN=https://apicr.minzdrav.gov.ru
      - REFERER=https://apicr.minzdrav.gov.ru/
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/var/log/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=clinical_recommendations
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d clinical_recommendations" ]  # Проверяем БД test
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: